// Generated by scripts/generate-contracts.mjs. Do not edit by hand.

export const AuditChainFixtureSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/audit-chain-fixture.schema.json",
  "title": "TaskOtterAuditChainFixture",
  "type": "object",
  "required": [
    "schema_version",
    "description",
    "chain",
    "prototype_paths",
    "negative_cases",
    "cross_repo_evidence",
    "events",
    "residual_risk"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "audit-chain-fixture@0.1.0"
    },
    "description": {
      "type": "string"
    },
    "chain": {
      "type": "object",
      "required": [
        "correlation_id",
        "request_id",
        "working_group_id",
        "actor",
        "run_id",
        "job_id",
        "runner_id",
        "gateway_request_id",
        "mcp_server_id",
        "policy_decision_id",
        "approval_id",
        "evidence_import_id",
        "review_packet_id",
        "done_decision_id",
        "rework_decision_id"
      ],
      "additionalProperties": false,
      "properties": {
        "correlation_id": {
          "$ref": "#/$defs/correlationId"
        },
        "request_id": {
          "$ref": "#/$defs/requestId"
        },
        "working_group_id": {
          "$ref": "#/$defs/workingGroupId"
        },
        "actor": {
          "$ref": "#/$defs/actorRef"
        },
        "run_id": {
          "$ref": "#/$defs/runId"
        },
        "job_id": {
          "$ref": "#/$defs/jobId"
        },
        "runner_id": {
          "$ref": "#/$defs/runnerId"
        },
        "gateway_request_id": {
          "$ref": "#/$defs/gatewayRequestId"
        },
        "mcp_server_id": {
          "$ref": "#/$defs/mcpServerId"
        },
        "policy_decision_id": {
          "$ref": "#/$defs/policyDecisionId"
        },
        "approval_id": {
          "$ref": "#/$defs/approvalId"
        },
        "evidence_import_id": {
          "$ref": "#/$defs/evidenceImportId"
        },
        "review_packet_id": {
          "$ref": "#/$defs/reviewPacketId"
        },
        "done_decision_id": {
          "$ref": "#/$defs/reviewDecisionId"
        },
        "rework_decision_id": {
          "$ref": "#/$defs/reviewDecisionId"
        }
      }
    },
    "prototype_paths": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/prototypePath"
      },
      "minItems": 4
    },
    "negative_cases": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/negativeCase"
      },
      "minItems": 2
    },
    "cross_repo_evidence": {
      "type": "object",
      "required": [
        "remote",
        "gateway"
      ],
      "additionalProperties": false,
      "properties": {
        "remote": {
          "type": "object",
          "required": [
            "repo",
            "protocol_version",
            "message_type",
            "fixture_path",
            "lineage_model",
            "required_control_plane_join_keys",
            "dispatch_payload_lineage"
          ],
          "additionalProperties": false,
          "properties": {
            "repo": {
              "const": "taskotter/taskotter-remote"
            },
            "protocol_version": {
              "const": "remote.v1alpha1"
            },
            "message_type": {
              "const": "job.dispatch"
            },
            "fixture_path": {
              "type": "string"
            },
            "lineage_model": {
              "const": "dispatch_fragment_requires_control_plane_join"
            },
            "required_control_plane_join_keys": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "correlation_id",
                  "request_id",
                  "working_group_id",
                  "policy_decision_id",
                  "job_id",
                  "runner_id"
                ]
              },
              "minItems": 6
            },
            "dispatch_payload_lineage": {
              "type": "object",
              "required": [
                "has_correlation_id",
                "has_request_id",
                "has_policy_decision_id",
                "has_working_group_id"
              ],
              "additionalProperties": false,
              "properties": {
                "has_correlation_id": {
                  "const": true
                },
                "has_request_id": {
                  "const": false
                },
                "has_policy_decision_id": {
                  "const": false
                },
                "has_working_group_id": {
                  "const": true
                }
              }
            }
          }
        },
        "gateway": {
          "type": "object",
          "required": [
            "repo",
            "protocol_version",
            "request_fixtures",
            "event_fixtures"
          ],
          "additionalProperties": false,
          "properties": {
            "repo": {
              "const": "taskotter/taskotter-gateway"
            },
            "protocol_version": {
              "const": "gateway.v0.1"
            },
            "request_fixtures": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 2
            },
            "event_fixtures": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 2
            }
          }
        }
      }
    },
    "events": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/chainEvent"
      },
      "minItems": 10
    },
    "residual_risk": {
      "type": "object",
      "required": [
        "export_delete_retention",
        "security_review_trigger",
        "security_review_reason"
      ],
      "additionalProperties": false,
      "properties": {
        "export_delete_retention": {
          "type": "string"
        },
        "security_review_trigger": {
          "const": true
        },
        "security_review_reason": {
          "type": "string"
        }
      }
    }
  },
  "$defs": {
    "safeOpaqueRef": {
      "type": "string",
      "maxLength": 120,
      "not": {
        "pattern": "(api[_-]?key|access[_-]?token|refresh[_-]?token|private[_-]?key|client[_-]?secret|bearer |password|raw[_-]?prompt|raw[_-]?log|artifact[_-]?body|transcript[_-]?copy|-----BEGIN)"
      }
    },
    "prototypePath": {
      "type": "object",
      "required": [
        "path",
        "terminal_state",
        "required_stages"
      ],
      "additionalProperties": false,
      "properties": {
        "path": {
          "$ref": "#/$defs/workflowPath"
        },
        "terminal_state": {
          "type": "string",
          "enum": [
            "done",
            "rework",
            "denied"
          ]
        },
        "required_stages": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/eventStage"
          },
          "minItems": 4
        }
      }
    },
    "workflowPath": {
      "type": "string",
      "enum": [
        "done_approved",
        "rework_requested",
        "missing_evidence",
        "denied"
      ]
    },
    "negativeCase": {
      "type": "object",
      "required": [
        "case",
        "target_stage",
        "operation",
        "field",
        "expected_error"
      ],
      "additionalProperties": false,
      "properties": {
        "case": {
          "type": "string",
          "enum": [
            "missing_correlation_id",
            "malformed_correlation_id"
          ]
        },
        "target_stage": {
          "$ref": "#/$defs/eventStage"
        },
        "operation": {
          "type": "string",
          "enum": [
            "remove_field",
            "set_field"
          ]
        },
        "field": {
          "const": "correlation_id"
        },
        "value": {
          "type": "string",
          "maxLength": 80
        },
        "expected_error": {
          "const": "correlation_id"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "operation": {
                "const": "set_field"
              }
            }
          },
          "then": {
            "required": [
              "value"
            ]
          }
        }
      ]
    },
    "eventStage": {
      "type": "string",
      "enum": [
        "user_request",
        "policy_decision",
        "plan_approval_requested",
        "plan_approved",
        "approval_requested",
        "runner_dispatch",
        "gateway_request",
        "mcp_call_denied",
        "usage_event",
        "audit_event",
        "artifact_log_event",
        "evidence_imported",
        "review_packet_generated",
        "human_decision_done",
        "evidence_missing",
        "human_decision_rework",
        "final_result"
      ]
    },
    "eventId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "correlationId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "requestId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "workingGroupId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "runId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^run_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "jobId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^job_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "runnerId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^runr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "gatewayRequestId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^gwreq_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "mcpServerId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^mcp_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "policyDecisionId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "approvalId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^appr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "evidenceImportId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^evimp_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "reviewPacketId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^rvpkt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "reviewDecisionId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^rvdec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "agent_run",
            "approval",
            "evidence_import",
            "human_decision",
            "gateway_request",
            "job",
            "mcp_server",
            "provider",
            "review_packet",
            "runner"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      }
    },
    "chainEvent": {
      "type": "object",
      "required": [
        "stage",
        "event_shape",
        "id",
        "type",
        "version",
        "occurred_at",
        "source",
        "working_group_id",
        "actor",
        "resource",
        "correlation_id",
        "request_id",
        "redaction",
        "payload"
      ],
      "additionalProperties": false,
      "properties": {
        "stage": {
          "$ref": "#/$defs/eventStage"
        },
        "event_shape": {
          "type": "string",
          "enum": [
            "summary_event",
            "canonical_event_reference"
          ]
        },
        "canonical_schema_path": {
          "type": "string"
        },
        "canonical_fixture_path": {
          "type": "string"
        },
        "id": {
          "$ref": "#/$defs/eventId"
        },
        "type": {
          "type": "string",
          "pattern": "^[a-z0-9]+(\\.[a-z0-9_]+)+$"
        },
        "version": {
          "const": "0.1.0"
        },
        "occurred_at": {
          "type": "string"
        },
        "source": {
          "type": "string",
          "enum": [
            "control_plane",
            "runner",
            "gateway"
          ]
        },
        "working_group_id": {
          "$ref": "#/$defs/workingGroupId"
        },
        "actor": {
          "$ref": "#/$defs/actorRef"
        },
        "resource": {
          "$ref": "#/$defs/resourceRef"
        },
        "correlation_id": {
          "$ref": "#/$defs/correlationId"
        },
        "request_id": {
          "$ref": "#/$defs/requestId"
        },
        "policy_decision_id": {
          "$ref": "#/$defs/policyDecisionId"
        },
        "approval_id": {
          "$ref": "#/$defs/approvalId"
        },
        "protocol_version": {
          "type": "string",
          "enum": [
            "remote.v1alpha1",
            "gateway.v0.1"
          ]
        },
        "redaction": {
          "type": "string",
          "enum": [
            "internal_reference_only",
            "redacted_summary"
          ]
        },
        "payload": {
          "type": "object"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "event_shape": {
                "const": "canonical_event_reference"
              }
            }
          },
          "then": {
            "required": [
              "canonical_schema_path",
              "canonical_fixture_path",
              "policy_decision_id"
            ]
          }
        }
      ]
    }
  }
} as const;

export const AuditEventSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/audit-event.schema.json",
  "title": "TaskOtterAuditEvent",
  "type": "object",
  "required": [
    "id",
    "type",
    "version",
    "occurred_at",
    "source",
    "working_group_id",
    "actor",
    "resource",
    "correlation_id",
    "request_id",
    "policy_decision_id",
    "payload"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "type": {
      "const": "audit.policy_decision.denied"
    },
    "version": {
      "const": "0.1.0"
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "correlation_id": {
      "type": "string",
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "request_id": {
      "type": "string",
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "policy_decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "payload": {
      "type": "object",
      "required": [
        "action",
        "outcome"
      ],
      "additionalProperties": false,
      "properties": {
        "action": {
          "type": "string"
        },
        "outcome": {
          "type": "string",
          "enum": [
            "allowed",
            "denied",
            "succeeded",
            "failed"
          ]
        },
        "runtime_capability": {
          "$ref": "#/$defs/highRiskRuntimeCapability"
        },
        "feature_flag": {
          "type": "string"
        },
        "approval_ref": {
          "type": "string"
        }
      }
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "highRiskRuntimeCapability": {
      "type": "string",
      "enum": [
        "remote.local_tool_execution",
        "remote.local_llm_exposure",
        "remote.external_agent_runtime_adapter",
        "remote.computer_use_execution",
        "gateway.hosted_mcp_billing",
        "gateway.sensitive_provider_routing"
      ]
    }
  }
} as const;

export const EventEnvelopeSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/event-envelope.schema.json",
  "title": "TaskOtterEventEnvelope",
  "type": "object",
  "required": [
    "id",
    "type",
    "version",
    "occurred_at",
    "source",
    "working_group_id",
    "actor",
    "resource",
    "correlation_id",
    "request_id",
    "payload"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "type": {
      "type": "string",
      "pattern": "^[a-z0-9]+(\\.[a-z0-9_]+)+$"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "correlation_id": {
      "type": "string",
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "request_id": {
      "type": "string",
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "idempotency_key": {
      "type": "string"
    },
    "policy_decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "payload": {
      "type": "object"
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    }
  }
} as const;

export const PolicyDecisionSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/policy-decision.schema.json",
  "title": "TaskOtterPolicyDecision",
  "type": "object",
  "required": [
    "schema_version",
    "decision_id",
    "working_group_id",
    "actor",
    "action",
    "resource",
    "effect",
    "policy_version",
    "policy_snapshot_id",
    "reason_code",
    "correlation_id",
    "request_id",
    "provenance",
    "evaluated_at",
    "ttl_seconds",
    "constraints"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "policy-decision@0.1.0"
    },
    "decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "action": {
      "type": "string",
      "examples": [
        "runner.job.execute",
        "gateway.provider.invoke"
      ]
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "effect": {
      "type": "string",
      "enum": [
        "allow",
        "deny"
      ]
    },
    "policy_version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "policy_snapshot_id": {
      "type": "string",
      "pattern": "^polsnap_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "reason_code": {
      "type": "string"
    },
    "correlation_id": {
      "type": "string",
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "request_id": {
      "type": "string",
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "provenance": {
      "type": "object",
      "required": [
        "source",
        "evaluated_by",
        "policy_bundle_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "source": {
          "type": "string",
          "enum": [
            "control_plane"
          ]
        },
        "evaluated_by": {
          "type": "string",
          "enum": [
            "policy_engine"
          ]
        },
        "policy_bundle_ref": {
          "type": "string"
        }
      }
    },
    "evaluated_at": {
      "type": "string",
      "format": "date-time"
    },
    "ttl_seconds": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3600
    },
    "constraints": {
      "type": "object",
      "required": [
        "network_zones",
        "tool_scopes",
        "provider_model_ids",
        "max_runtime_seconds"
      ],
      "additionalProperties": false,
      "properties": {
        "network_zones": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tool_scopes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "provider_model_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "high_risk_capabilities": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/highRiskCapabilityGate"
          }
        },
        "max_runtime_seconds": {
          "type": "integer",
          "minimum": 1
        }
      }
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "highRiskCapabilityGate": {
      "type": "object",
      "required": [
        "capability",
        "feature_flag",
        "enabled",
        "effect",
        "metering_unit"
      ],
      "additionalProperties": false,
      "properties": {
        "capability": {
          "type": "string",
          "enum": [
            "remote.local_tool_execution",
            "remote.local_llm_exposure",
            "remote.external_agent_runtime_adapter",
            "remote.computer_use_execution",
            "gateway.hosted_mcp_billing",
            "gateway.sensitive_provider_routing"
          ]
        },
        "feature_flag": {
          "type": "string",
          "enum": [
            "remote.local_tools.enabled",
            "remote.local_llm.enabled",
            "remote.external_agent_adapters.enabled",
            "remote.computer_use.enabled",
            "gateway.hosted_mcp_billing.enabled",
            "gateway.provider_routing.enabled"
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "effect": {
          "type": "string",
          "enum": [
            "allow",
            "deny"
          ]
        },
        "approval_ref": {
          "type": "string"
        },
        "metering_unit": {
          "type": "string",
          "enum": [
            "request",
            "tool_invocation",
            "runtime_ms",
            "local_compute_ms",
            "hosted_mcp_runtime_ms",
            "token"
          ]
        }
      }
    }
  }
} as const;

export const ReviewPacketSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/review-packet.schema.json",
  "title": "TaskOtterReviewPacket",
  "type": "object",
  "required": [
    "schema_version",
    "packet_id",
    "work_item",
    "plan_approval",
    "acceptance_criteria",
    "evidence_sources",
    "result_summary",
    "rollback_path",
    "decision",
    "audit_events",
    "raw_content_boundary",
    "compatibility"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "review-packet@0.1.0"
    },
    "packet_id": {
      "$ref": "#/$defs/reviewPacketId"
    },
    "work_item": {
      "type": "object",
      "required": [
        "work_item_id",
        "source_category",
        "source_ref",
        "summary_ref",
        "risk_tier"
      ],
      "additionalProperties": false,
      "properties": {
        "work_item_id": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "source_category": {
          "$ref": "#/$defs/sourceCategory"
        },
        "source_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "summary_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "risk_tier": {
          "$ref": "#/$defs/riskTier"
        }
      }
    },
    "plan_approval": {
      "type": "object",
      "required": [
        "state",
        "approval_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "state": {
          "type": "string",
          "enum": [
            "pending",
            "approved",
            "not_required"
          ]
        },
        "approval_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      }
    },
    "acceptance_criteria": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/acceptanceCriterion"
      },
      "minItems": 1
    },
    "evidence_sources": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/evidenceSource"
      },
      "minItems": 1
    },
    "result_summary": {
      "type": "object",
      "required": [
        "summary_ref",
        "status",
        "changed_area_refs"
      ],
      "additionalProperties": false,
      "properties": {
        "summary_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "status": {
          "type": "string",
          "enum": [
            "ready_for_review",
            "needs_rework",
            "blocked"
          ]
        },
        "changed_area_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/safeOpaqueRef"
          },
          "minItems": 1
        }
      }
    },
    "rollback_path": {
      "type": "object",
      "required": [
        "available",
        "summary_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "available": {
          "type": "boolean"
        },
        "summary_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      }
    },
    "decision": {
      "type": "object",
      "required": [
        "outcome",
        "decision_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "outcome": {
          "type": "string",
          "enum": [
            "pending",
            "done",
            "rework",
            "blocked"
          ]
        },
        "decision_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "reason_code": {
          "type": "string",
          "enum": [
            "acceptance_criteria_met",
            "missing_required_evidence",
            "residual_risk",
            "reviewer_requested_rework"
          ]
        }
      }
    },
    "audit_events": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/auditEventRef"
      },
      "minItems": 1
    },
    "raw_content_boundary": {
      "type": "object",
      "required": [
        "raw_transcript_storage",
        "full_diff_storage",
        "allowed_reference_fields",
        "forbidden_payload_fields"
      ],
      "additionalProperties": false,
      "properties": {
        "raw_transcript_storage": {
          "const": "reference_only"
        },
        "full_diff_storage": {
          "const": "reference_only"
        },
        "allowed_reference_fields": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "summary_ref",
              "artifact_manifest_ref",
              "diff_summary_ref",
              "test_result_ref",
              "audit_event_ref"
            ]
          },
          "minItems": 3
        },
        "forbidden_payload_fields": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "raw_transcript",
              "full_diff",
              "secret_value",
              "customer_data",
              "private_roadmap_body"
            ]
          },
          "minItems": 5
        }
      }
    },
    "compatibility": {
      "type": "object",
      "required": [
        "versioning_strategy",
        "breaking_change_policy"
      ],
      "additionalProperties": false,
      "properties": {
        "versioning_strategy": {
          "const": "additive_minor_fields_only"
        },
        "breaking_change_policy": {
          "const": "new_major_schema_version"
        }
      }
    }
  },
  "$defs": {
    "safeOpaqueRef": {
      "type": "string",
      "maxLength": 120,
      "not": {
        "pattern": "([aA][pP][iI][ _-]?[kK][eE][yY]|[aA][cC][cC][eE][sS][sS][ _-]?[tT][oO][kK][eE][nN]|[rR][eE][fF][rR][eE][sS][hH][ _-]?[tT][oO][kK][eE][nN]|[pP][rR][iI][vV][aA][tT][eE][ _-]?[kK][eE][yY]|[cC][lL][iI][eE][nN][tT][ _-]?[sS][eE][cC][rR][eE][tT]|[bB][eE][aA][rR][eE][rR]\\s+|[pP][aA][sS][sS][wW][oO][rR][dD]|[rR][aA][wW][ _-]?[pP][rR][oO][mM][pP][tT]|[rR][aA][wW][ _-]?[lL][oO][gG]|[rR][aA][wW][ _-]?[tT][rR][aA][nN][sS][cC][rR][iI][pP][tT]|[fF][uU][lL][lL][ _-]?[dD][iI][fF][fF]|[aA][rR][tT][iI][fF][aA][cC][tT][ _-]?[bB][oO][dD][yY]|[tT][rR][aA][nN][sS][cC][rR][iI][pP][tT][ _-]?[cC][oO][pP][yY]|[sS][eE][cC][rR][eE][tT][ _-]?[vV][aA][lL][uU][eE]|[cC][uU][sS][tT][oO][mM][eE][rR][ _-]?[dD][aA][tT][aA]|[pP][rR][iI][vV][aA][tT][eE][ _-]?[rR][oO][aA][dD][mM][aA][pP]|-----[bB][eE][gG][iI][nN])"
      }
    },
    "reviewPacketId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^rvpkt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "auditEventId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "sourceCategory": {
      "type": "string",
      "enum": [
        "multica_issue",
        "github_issue",
        "agent_run",
        "manual"
      ]
    },
    "riskTier": {
      "type": "string",
      "enum": [
        "low",
        "medium",
        "high",
        "critical"
      ]
    },
    "acceptanceCriterion": {
      "type": "object",
      "required": [
        "criterion_id",
        "summary_ref",
        "status",
        "required"
      ],
      "additionalProperties": false,
      "properties": {
        "criterion_id": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "summary_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "status": {
          "type": "string",
          "enum": [
            "met",
            "not_met",
            "unknown"
          ]
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "evidenceSource": {
      "type": "object",
      "required": [
        "source_category",
        "evidence_ref",
        "summary_ref",
        "risk_signals",
        "uncertainty"
      ],
      "additionalProperties": false,
      "properties": {
        "source_category": {
          "type": "string",
          "enum": [
            "test_result",
            "generated_schema",
            "fixture_validation",
            "human_note",
            "audit_event",
            "diff_summary",
            "module_guard"
          ]
        },
        "evidence_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "summary_ref": {
          "$ref": "#/$defs/safeOpaqueRef"
        },
        "risk_signals": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "contract_change",
              "schema_generation",
              "security_sensitive",
              "module_boundary",
              "file_size_guard",
              "residual_risk"
            ]
          }
        },
        "uncertainty": {
          "type": "string",
          "enum": [
            "low",
            "medium",
            "high"
          ]
        }
      }
    },
    "auditEventRef": {
      "type": "object",
      "required": [
        "event_id",
        "event_type",
        "event_version"
      ],
      "additionalProperties": false,
      "properties": {
        "event_id": {
          "$ref": "#/$defs/auditEventId"
        },
        "event_type": {
          "type": "string",
          "pattern": "^[a-z0-9]+(\\.[a-z0-9_]+)+$"
        },
        "event_version": {
          "const": "0.1.0"
        }
      }
    }
  }
} as const;

export const UsageEventSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/usage-event.schema.json",
  "title": "TaskOtterUsageEvent",
  "type": "object",
  "required": [
    "id",
    "type",
    "version",
    "occurred_at",
    "source",
    "working_group_id",
    "actor",
    "resource",
    "correlation_id",
    "request_id",
    "policy_decision_id",
    "idempotency_key",
    "payload"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "$ref": "#/$defs/eventId"
    },
    "type": {
      "const": "usage.gateway_request.recorded"
    },
    "version": {
      "const": "0.1.0"
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "working_group_id": {
      "$ref": "#/$defs/workingGroupId"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "correlation_id": {
      "$ref": "#/$defs/correlationId"
    },
    "request_id": {
      "$ref": "#/$defs/requestId"
    },
    "policy_decision_id": {
      "$ref": "#/$defs/policyDecisionId"
    },
    "idempotency_key": {
      "$ref": "#/$defs/idempotencyKey"
    },
    "reservation_id": {
      "$ref": "#/$defs/reservationId"
    },
    "status": {
      "$ref": "#/$defs/usageAttemptStatus"
    },
    "denial_reason": {
      "$ref": "#/$defs/denialReason"
    },
    "payload": {
      "type": "object",
      "required": [
        "subject",
        "measurements"
      ],
      "additionalProperties": false,
      "properties": {
        "subject": {
          "$ref": "#/$defs/usageSubjectRef"
        },
        "measurements": {
          "type": "object",
          "required": [
            "duration_ms"
          ],
          "additionalProperties": false,
          "properties": {
            "duration_ms": {
              "type": "integer",
              "minimum": 0
            },
            "input_tokens": {
              "type": "integer",
              "minimum": 0
            },
            "output_tokens": {
              "type": "integer",
              "minimum": 0
            },
            "tool_invocations": {
              "type": "integer",
              "minimum": 0
            },
            "estimated_cost_micros": {
              "type": "integer",
              "minimum": 0
            },
            "actual_cost_micros": {
              "type": "integer",
              "minimum": 0
            },
            "metering_unit": {
              "$ref": "#/$defs/meteringUnit"
            },
            "runtime_capability": {
              "$ref": "#/$defs/highRiskRuntimeCapability"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "safeOpaqueRef": {
      "type": "string",
      "maxLength": 80,
      "not": {
        "pattern": "(api[_-]?key|access[_-]?token|refresh[_-]?token|private[_-]?key|client[_-]?secret|bearer |password|raw[_-]?prompt|raw[_-]?log|artifact[_-]?body|-----BEGIN)"
      }
    },
    "eventId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "workingGroupId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "correlationId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "requestId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "policyDecisionId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "idempotencyKey": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^usage_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "reservationId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^resv_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "user"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^usr_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "agent"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^agt_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "service"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^svc_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        }
      ]
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "provider",
            "mcp_server",
            "runner",
            "job",
            "integration"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "provider"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^prv_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "mcp_server"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^mcp_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "runner"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^runr_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "job"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^job_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "integration"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^int_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        }
      ]
    },
    "usageSubjectRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "agent_run",
            "gateway_request",
            "workflow_run",
            "runner_job"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "agent_run"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^run_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "gateway_request"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^gwreq_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "workflow_run"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^wfrun_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "runner_job"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^job_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        }
      ]
    },
    "usageAttemptStatus": {
      "type": "string",
      "enum": [
        "succeeded",
        "denied",
        "timeout",
        "cancelled",
        "failed"
      ]
    },
    "denialReason": {
      "type": "string",
      "maxLength": 80,
      "enum": [
        "policy_denied",
        "usage_limit_reached",
        "protected_capability_disabled",
        "quota_exceeded"
      ]
    },
    "highRiskRuntimeCapability": {
      "type": "string",
      "maxLength": 80,
      "enum": [
        "remote.local_tool_execution",
        "remote.local_llm_exposure",
        "remote.external_agent_runtime_adapter",
        "remote.computer_use_execution",
        "gateway.hosted_mcp_billing",
        "gateway.sensitive_provider_routing"
      ]
    },
    "meteringUnit": {
      "type": "string",
      "enum": [
        "request",
        "tool_invocation",
        "runtime_ms",
        "local_compute_ms",
        "hosted_mcp_runtime_ms",
        "token"
      ]
    }
  }
} as const;

export const WorkflowDefinitionSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/workflow-definition.schema.json",
  "title": "TaskOtterWorkflowDefinition",
  "description": "Canonical parsed representation for portable TaskOtter workflow YAML. This contract defines authoring and validation shape only; scheduler and worker execution remain separate runtime responsibilities.",
  "type": "object",
  "required": [
    "schema_version",
    "workflow_id",
    "working_group_id",
    "name",
    "status",
    "portable_format",
    "service_identity",
    "triggers",
    "concurrency",
    "approval_gates",
    "jobs",
    "audit_events"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "workflow-definition@0.1.0"
    },
    "workflow_id": {
      "type": "string",
      "pattern": "^wfl_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "draft",
        "active",
        "disabled",
        "archived"
      ]
    },
    "portable_format": {
      "type": "string",
      "enum": [
        "yaml"
      ]
    },
    "service_identity": {
      "$ref": "#/$defs/serviceIdentity"
    },
    "triggers": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/trigger"
      }
    },
    "concurrency": {
      "$ref": "#/$defs/concurrency"
    },
    "defaults": {
      "$ref": "#/$defs/executionDefaults"
    },
    "approval_gates": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/approvalGate"
      }
    },
    "jobs": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/job"
      }
    },
    "audit_events": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/auditEventReference"
      }
    }
  },
  "$defs": {
    "workflowLocalId": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9_\\-]{1,63}$"
    },
    "refName": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9_\\-./]{1,127}$"
    },
    "expression": {
      "type": "string",
      "minLength": 1
    },
    "serviceIdentity": {
      "type": "object",
      "required": [
        "type",
        "id",
        "delegation"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "service_account",
            "delegated_actor"
          ]
        },
        "id": {
          "type": "string"
        },
        "delegation": {
          "type": "object",
          "required": [
            "preserve_triggering_principal"
          ],
          "additionalProperties": false,
          "properties": {
            "preserve_triggering_principal": {
              "type": "boolean",
              "const": true
            }
          }
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "secretRef": {
      "type": "object",
      "description": "Pointer to centrally managed secret material. Raw secret values, tokens, keys, and credentials are not allowed in workflow definitions or fixtures.",
      "required": [
        "secret_ref",
        "purpose"
      ],
      "additionalProperties": false,
      "properties": {
        "secret_ref": {
          "type": "string",
          "pattern": "^sec_[0-9A-HJKMNP-TV-Z]{26}$"
        },
        "purpose": {
          "type": "string"
        }
      }
    },
    "integrationRef": {
      "type": "object",
      "required": [
        "integration_ref",
        "purpose"
      ],
      "additionalProperties": false,
      "properties": {
        "integration_ref": {
          "type": "string",
          "pattern": "^int_[0-9A-HJKMNP-TV-Z]{26}$"
        },
        "purpose": {
          "type": "string"
        }
      }
    },
    "policyCheck": {
      "type": "object",
      "required": [
        "action",
        "resource",
        "decision_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "action": {
          "type": "string"
        },
        "resource": {
          "$ref": "#/$defs/resourceRef"
        },
        "decision_ref": {
          "$ref": "#/$defs/refName"
        }
      }
    },
    "retryPolicy": {
      "type": "object",
      "required": [
        "max_attempts",
        "backoff"
      ],
      "additionalProperties": false,
      "properties": {
        "max_attempts": {
          "type": "integer",
          "minimum": 1,
          "maximum": 10
        },
        "backoff": {
          "type": "string",
          "enum": [
            "none",
            "linear",
            "exponential"
          ]
        },
        "idempotency_required": {
          "type": "boolean"
        }
      }
    },
    "executionDefaults": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "timeout_seconds": {
          "type": "integer",
          "minimum": 1
        },
        "retry": {
          "$ref": "#/$defs/retryPolicy"
        }
      }
    },
    "concurrency": {
      "type": "object",
      "required": [
        "scope",
        "limit",
        "on_conflict"
      ],
      "additionalProperties": false,
      "properties": {
        "scope": {
          "type": "string",
          "enum": [
            "workflow",
            "working_group",
            "trigger"
          ]
        },
        "limit": {
          "type": "integer",
          "minimum": 1
        },
        "on_conflict": {
          "type": "string",
          "enum": [
            "queue",
            "cancel_new",
            "cancel_running"
          ]
        }
      }
    },
    "trigger": {
      "type": "object",
      "required": [
        "id",
        "type",
        "enabled"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "type": {
          "type": "string",
          "enum": [
            "cron",
            "webhook",
            "internal_event"
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "filters": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/expression"
          }
        },
        "cron": {
          "type": "object",
          "required": [
            "schedule",
            "timezone"
          ],
          "additionalProperties": false,
          "properties": {
            "schedule": {
              "type": "string",
              "minLength": 1
            },
            "timezone": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "webhook": {
          "type": "object",
          "required": [
            "integration_ref",
            "signature_verification",
            "replay_protection"
          ],
          "additionalProperties": false,
          "properties": {
            "integration_ref": {
              "$ref": "#/$defs/integrationRef"
            },
            "signature_verification": {
              "type": "object",
              "required": [
                "required",
                "algorithm",
                "secret_ref"
              ],
              "additionalProperties": false,
              "properties": {
                "required": {
                  "type": "boolean",
                  "const": true
                },
                "algorithm": {
                  "type": "string",
                  "enum": [
                    "hmac-sha256",
                    "ed25519"
                  ]
                },
                "secret_ref": {
                  "$ref": "#/$defs/secretRef"
                },
                "timestamp_header": {
                  "type": "string"
                },
                "signature_header": {
                  "type": "string"
                }
              }
            },
            "replay_protection": {
              "type": "object",
              "required": [
                "required",
                "dedupe_key",
                "window_seconds"
              ],
              "additionalProperties": false,
              "properties": {
                "required": {
                  "type": "boolean",
                  "const": true
                },
                "dedupe_key": {
                  "type": "string",
                  "enum": [
                    "event_id",
                    "delivery_id",
                    "signature_digest"
                  ]
                },
                "window_seconds": {
                  "type": "integer",
                  "minimum": 60,
                  "maximum": 86400
                }
              }
            }
          }
        },
        "internal_event": {
          "type": "object",
          "required": [
            "event_type"
          ],
          "additionalProperties": false,
          "properties": {
            "event_type": {
              "type": "string",
              "enum": [
                "issue.created",
                "issue.updated",
                "issue.status_changed",
                "comment.created",
                "user.created",
                "working_group.changed",
                "integration.changed",
                "skill.changed",
                "agent.changed",
                "provider.changed",
                "usage.limit_reached",
                "policy.decision_denied",
                "workflow.completed",
                "workflow.failed"
              ]
            }
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "cron"
              }
            }
          },
          "then": {
            "required": [
              "cron"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "webhook"
              }
            }
          },
          "then": {
            "required": [
              "webhook"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "internal_event"
              }
            }
          },
          "then": {
            "required": [
              "internal_event"
            ]
          }
        }
      ]
    },
    "approvalGate": {
      "type": "object",
      "required": [
        "id",
        "approver_scope",
        "required_before",
        "timeout_seconds",
        "on_timeout"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "approver_scope": {
          "type": "string",
          "enum": [
            "workflow_owner",
            "working_group_admin",
            "policy_named_role"
          ]
        },
        "required_before": {
          "type": "string",
          "enum": [
            "protected_side_effect",
            "workflow_activation",
            "manual_review"
          ]
        },
        "timeout_seconds": {
          "type": "integer",
          "minimum": 60
        },
        "on_timeout": {
          "type": "string",
          "enum": [
            "deny",
            "cancel_run"
          ]
        },
        "reason": {
          "type": "string"
        }
      }
    },
    "job": {
      "type": "object",
      "required": [
        "id",
        "name",
        "steps"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "needs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/workflowLocalId"
          }
        },
        "condition": {
          "$ref": "#/$defs/expression"
        },
        "timeout_seconds": {
          "type": "integer",
          "minimum": 1
        },
        "retry": {
          "$ref": "#/$defs/retryPolicy"
        },
        "policy": {
          "$ref": "#/$defs/policyCheck"
        },
        "steps": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/step"
          }
        }
      }
    },
    "step": {
      "type": "object",
      "required": [
        "id",
        "kind",
        "name",
        "side_effect"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "kind": {
          "type": "string",
          "enum": [
            "agent_task",
            "approval_wait",
            "policy_check",
            "gateway_request",
            "integration_call",
            "mcp_call",
            "script",
            "artifact_write",
            "handoff",
            "audit_event"
          ]
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "uses": {
          "$ref": "#/$defs/refName"
        },
        "needs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/workflowLocalId"
          }
        },
        "condition": {
          "$ref": "#/$defs/expression"
        },
        "timeout_seconds": {
          "type": "integer",
          "minimum": 1
        },
        "retry": {
          "$ref": "#/$defs/retryPolicy"
        },
        "policy": {
          "$ref": "#/$defs/policyCheck"
        },
        "approval_gate_ref": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "secret_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/secretRef"
          }
        },
        "integration_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/integrationRef"
          }
        },
        "with": {
          "$ref": "#/$defs/nonSecretInputObject"
        },
        "side_effect": {
          "type": "object",
          "required": [
            "classification"
          ],
          "additionalProperties": false,
          "properties": {
            "classification": {
              "type": "string",
              "enum": [
                "none",
                "read",
                "write",
                "protected"
              ]
            },
            "description": {
              "type": "string"
            }
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "side_effect": {
                "properties": {
                  "classification": {
                    "const": "protected"
                  }
                }
              }
            }
          },
          "then": {
            "required": [
              "approval_gate_ref"
            ]
          }
        }
      ]
    },
    "nonSecretInputObject": {
      "type": "object",
      "description": "Non-secret step inputs. Sensitive values must be represented through secret_refs or integration_refs.",
      "propertyNames": {
        "not": {
          "pattern": "([Aa][Pp][Ii][_-]?[Kk][Ee][Yy]|[Aa][Cc][Cc][Ee][Ss][Ss][_-]?[Tt][Oo][Kk][Ee][Nn]|[Rr][Ee][Ff][Rr][Ee][Ss][Hh][_-]?[Tt][Oo][Kk][Ee][Nn]|[Pp][Rr][Ii][Vv][Aa][Tt][Ee][_-]?[Kk][Ee][Yy]|[Cc][Ll][Ii][Ee][Nn][Tt][_-]?[Ss][Ee][Cc][Rr][Ee][Tt]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Cc][Rr][Ee][Dd][Ee][Nn][Tt][Ii][Aa][Ll])"
        }
      },
      "additionalProperties": {
        "$ref": "#/$defs/nonSecretInputValue"
      }
    },
    "nonSecretInputValue": {
      "oneOf": [
        {
          "type": "string",
          "not": {
            "pattern": "([Bb][Ee][Aa][Rr][Ee][Rr]\\s+[A-Za-z0-9._\\-]+|gh[pousr]_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9_\\-]{16,}|-----BEGIN [A-Z ]*PRIVATE KEY-----)"
          }
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        },
        {
          "type": "null"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonSecretInputValue"
          }
        },
        {
          "$ref": "#/$defs/nonSecretInputObject"
        }
      ]
    },
    "auditEventReference": {
      "type": "object",
      "required": [
        "type",
        "resource",
        "when"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "workflow.definition.validated",
            "workflow.trigger.accepted",
            "workflow.approval.requested",
            "workflow.protected_operation.approved",
            "workflow.protected_operation.denied",
            "workflow.run.completed",
            "workflow.run.failed"
          ]
        },
        "resource": {
          "$ref": "#/$defs/resourceRef"
        },
        "when": {
          "type": "string",
          "enum": [
            "validation",
            "trigger",
            "approval",
            "completion"
          ]
        }
      }
    }
  }
} as const;

export const contractSchemas = {
  "audit-chain-fixture.schema.json": AuditChainFixtureSchema,
  "audit-event.schema.json": AuditEventSchema,
  "event-envelope.schema.json": EventEnvelopeSchema,
  "policy-decision.schema.json": PolicyDecisionSchema,
  "review-packet.schema.json": ReviewPacketSchema,
  "usage-event.schema.json": UsageEventSchema,
  "workflow-definition.schema.json": WorkflowDefinitionSchema
} as const;
