// Generated by scripts/generate-contracts.mjs. Do not edit by hand.

export const AuditEventSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/audit-event.schema.json",
  "title": "TaskOtterAuditEvent",
  "type": "object",
  "required": [
    "id",
    "type",
    "version",
    "occurred_at",
    "source",
    "working_group_id",
    "actor",
    "resource",
    "correlation_id",
    "request_id",
    "policy_decision_id",
    "payload"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "type": {
      "const": "audit.policy_decision.denied"
    },
    "version": {
      "const": "0.1.0"
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "correlation_id": {
      "type": "string",
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "request_id": {
      "type": "string",
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "policy_decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "payload": {
      "type": "object",
      "required": [
        "action",
        "outcome"
      ],
      "additionalProperties": false,
      "properties": {
        "action": {
          "type": "string"
        },
        "outcome": {
          "type": "string",
          "enum": [
            "allowed",
            "denied",
            "succeeded",
            "failed"
          ]
        },
        "runtime_capability": {
          "$ref": "#/$defs/highRiskRuntimeCapability"
        },
        "feature_flag": {
          "type": "string"
        },
        "approval_ref": {
          "type": "string"
        }
      }
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "highRiskRuntimeCapability": {
      "type": "string",
      "enum": [
        "remote.local_tool_execution",
        "remote.local_llm_exposure",
        "remote.external_agent_runtime_adapter",
        "remote.computer_use_execution",
        "gateway.hosted_mcp_billing",
        "gateway.sensitive_provider_routing"
      ]
    }
  }
} as const;

export const EventEnvelopeSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/event-envelope.schema.json",
  "title": "TaskOtterEventEnvelope",
  "type": "object",
  "required": [
    "id",
    "type",
    "version",
    "occurred_at",
    "source",
    "working_group_id",
    "actor",
    "resource",
    "correlation_id",
    "request_id",
    "payload"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "type": {
      "type": "string",
      "pattern": "^[a-z0-9]+(\\.[a-z0-9_]+)+$"
    },
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "correlation_id": {
      "type": "string",
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "request_id": {
      "type": "string",
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "idempotency_key": {
      "type": "string"
    },
    "policy_decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "payload": {
      "type": "object"
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    }
  }
} as const;

export const PolicyDecisionSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/policy-decision.schema.json",
  "title": "TaskOtterPolicyDecision",
  "type": "object",
  "required": [
    "schema_version",
    "decision_id",
    "working_group_id",
    "actor",
    "action",
    "resource",
    "effect",
    "policy_version",
    "policy_snapshot_id",
    "reason_code",
    "correlation_id",
    "request_id",
    "provenance",
    "evaluated_at",
    "ttl_seconds",
    "constraints"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "policy-decision@0.1.0"
    },
    "decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "action": {
      "type": "string",
      "examples": [
        "runner.job.execute",
        "gateway.provider.invoke"
      ]
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "effect": {
      "type": "string",
      "enum": [
        "allow",
        "deny"
      ]
    },
    "policy_version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$"
    },
    "policy_snapshot_id": {
      "type": "string",
      "pattern": "^polsnap_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "reason_code": {
      "type": "string"
    },
    "correlation_id": {
      "type": "string",
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "request_id": {
      "type": "string",
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "provenance": {
      "type": "object",
      "required": [
        "source",
        "evaluated_by",
        "policy_bundle_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "source": {
          "type": "string",
          "enum": [
            "control_plane"
          ]
        },
        "evaluated_by": {
          "type": "string",
          "enum": [
            "policy_engine"
          ]
        },
        "policy_bundle_ref": {
          "type": "string"
        }
      }
    },
    "evaluated_at": {
      "type": "string",
      "format": "date-time"
    },
    "ttl_seconds": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3600
    },
    "constraints": {
      "type": "object",
      "required": [
        "network_zones",
        "tool_scopes",
        "provider_model_ids",
        "max_runtime_seconds"
      ],
      "additionalProperties": false,
      "properties": {
        "network_zones": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tool_scopes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "provider_model_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "high_risk_capabilities": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/highRiskCapabilityGate"
          }
        },
        "max_runtime_seconds": {
          "type": "integer",
          "minimum": 1
        }
      }
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "highRiskCapabilityGate": {
      "type": "object",
      "required": [
        "capability",
        "feature_flag",
        "enabled",
        "effect",
        "metering_unit"
      ],
      "additionalProperties": false,
      "properties": {
        "capability": {
          "type": "string",
          "enum": [
            "remote.local_tool_execution",
            "remote.local_llm_exposure",
            "remote.external_agent_runtime_adapter",
            "remote.computer_use_execution",
            "gateway.hosted_mcp_billing",
            "gateway.sensitive_provider_routing"
          ]
        },
        "feature_flag": {
          "type": "string",
          "enum": [
            "remote.local_tools.enabled",
            "remote.local_llm.enabled",
            "remote.external_agent_adapters.enabled",
            "remote.computer_use.enabled",
            "gateway.hosted_mcp_billing.enabled",
            "gateway.provider_routing.enabled"
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "effect": {
          "type": "string",
          "enum": [
            "allow",
            "deny"
          ]
        },
        "approval_ref": {
          "type": "string"
        },
        "metering_unit": {
          "type": "string",
          "enum": [
            "request",
            "tool_invocation",
            "runtime_ms",
            "local_compute_ms",
            "hosted_mcp_runtime_ms",
            "token"
          ]
        }
      }
    }
  }
} as const;

export const UsageEventSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/usage-event.schema.json",
  "title": "TaskOtterUsageEvent",
  "type": "object",
  "required": [
    "id",
    "type",
    "version",
    "occurred_at",
    "source",
    "working_group_id",
    "actor",
    "resource",
    "correlation_id",
    "request_id",
    "policy_decision_id",
    "idempotency_key",
    "payload"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "$ref": "#/$defs/eventId"
    },
    "type": {
      "const": "usage.gateway_request.recorded"
    },
    "version": {
      "const": "0.1.0"
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "working_group_id": {
      "$ref": "#/$defs/workingGroupId"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "correlation_id": {
      "$ref": "#/$defs/correlationId"
    },
    "request_id": {
      "$ref": "#/$defs/requestId"
    },
    "policy_decision_id": {
      "$ref": "#/$defs/policyDecisionId"
    },
    "idempotency_key": {
      "$ref": "#/$defs/idempotencyKey"
    },
    "reservation_id": {
      "$ref": "#/$defs/reservationId"
    },
    "status": {
      "$ref": "#/$defs/usageAttemptStatus"
    },
    "denial_reason": {
      "$ref": "#/$defs/denialReason"
    },
    "payload": {
      "type": "object",
      "required": [
        "subject",
        "measurements"
      ],
      "additionalProperties": false,
      "properties": {
        "subject": {
          "$ref": "#/$defs/usageSubjectRef"
        },
        "measurements": {
          "type": "object",
          "required": [
            "duration_ms"
          ],
          "additionalProperties": false,
          "properties": {
            "duration_ms": {
              "type": "integer",
              "minimum": 0
            },
            "input_tokens": {
              "type": "integer",
              "minimum": 0
            },
            "output_tokens": {
              "type": "integer",
              "minimum": 0
            },
            "tool_invocations": {
              "type": "integer",
              "minimum": 0
            },
            "estimated_cost_micros": {
              "type": "integer",
              "minimum": 0
            },
            "actual_cost_micros": {
              "type": "integer",
              "minimum": 0
            },
            "metering_unit": {
              "$ref": "#/$defs/meteringUnit"
            },
            "runtime_capability": {
              "$ref": "#/$defs/highRiskRuntimeCapability"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "safeOpaqueRef": {
      "type": "string",
      "maxLength": 80,
      "not": {
        "pattern": "(api[_-]?key|access[_-]?token|refresh[_-]?token|private[_-]?key|client[_-]?secret|bearer |password|raw[_-]?prompt|raw[_-]?log|artifact[_-]?body|-----BEGIN|[Xx]-[Aa][Mm][Zz]-[Ss][Ii][Gg][Nn][Aa][Tt][Uu][Rr][Ee]|[Xx]-[Gg][Oo][Oo][Gg]-[Ss][Ii][Gg][Nn][Aa][Tt][Uu][Rr][Ee]|[Ss][Ii][Gg][Nn][Aa][Tt][Uu][Rr][Ee]=)"
      }
    },
    "eventId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^evt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "workingGroupId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "correlationId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^corr_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "requestId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^req_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "policyDecisionId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "idempotencyKey": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^usage_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "reservationId": {
      "allOf": [
        {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      ],
      "pattern": "^resv_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "user"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^usr_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "agent"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^agt_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "service"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^svc_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        }
      ]
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "provider",
            "mcp_server",
            "runner",
            "job",
            "integration"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "provider"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^prv_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "mcp_server"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^mcp_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "runner"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^runr_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "job"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^job_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "integration"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^int_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        }
      ]
    },
    "usageSubjectRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "agent_run",
            "gateway_request",
            "workflow_run",
            "runner_job"
          ]
        },
        "id": {
          "$ref": "#/$defs/safeOpaqueRef"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "agent_run"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^run_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "gateway_request"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^gwreq_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "workflow_run"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^wfrun_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "runner_job"
              }
            }
          },
          "then": {
            "properties": {
              "id": {
                "pattern": "^job_[0-9A-HJKMNP-TV-Z]{26}$"
              }
            }
          }
        }
      ]
    },
    "usageAttemptStatus": {
      "type": "string",
      "enum": [
        "succeeded",
        "denied",
        "timeout",
        "cancelled",
        "failed"
      ]
    },
    "denialReason": {
      "type": "string",
      "maxLength": 80,
      "enum": [
        "policy_denied",
        "usage_limit_reached",
        "protected_capability_disabled",
        "quota_exceeded"
      ]
    },
    "highRiskRuntimeCapability": {
      "type": "string",
      "maxLength": 80,
      "enum": [
        "remote.local_tool_execution",
        "remote.local_llm_exposure",
        "remote.external_agent_runtime_adapter",
        "remote.computer_use_execution",
        "gateway.hosted_mcp_billing",
        "gateway.sensitive_provider_routing"
      ]
    },
    "meteringUnit": {
      "type": "string",
      "enum": [
        "request",
        "tool_invocation",
        "runtime_ms",
        "local_compute_ms",
        "hosted_mcp_runtime_ms",
        "token"
      ]
    }
  }
} as const;

export const WorkflowDefinitionSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/workflow-definition.schema.json",
  "title": "TaskOtterWorkflowDefinition",
  "description": "Canonical parsed representation for portable TaskOtter workflow YAML. This contract defines authoring and validation shape only; scheduler and worker execution remain separate runtime responsibilities.",
  "type": "object",
  "required": [
    "schema_version",
    "workflow_id",
    "working_group_id",
    "name",
    "status",
    "portable_format",
    "service_identity",
    "triggers",
    "concurrency",
    "approval_gates",
    "jobs",
    "audit_events"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "workflow-definition@0.1.0"
    },
    "workflow_id": {
      "type": "string",
      "pattern": "^wfl_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "enum": [
        "draft",
        "active",
        "disabled",
        "archived"
      ]
    },
    "portable_format": {
      "type": "string",
      "enum": [
        "yaml"
      ]
    },
    "service_identity": {
      "$ref": "#/$defs/serviceIdentity"
    },
    "triggers": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/trigger"
      }
    },
    "concurrency": {
      "$ref": "#/$defs/concurrency"
    },
    "defaults": {
      "$ref": "#/$defs/executionDefaults"
    },
    "approval_gates": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/approvalGate"
      }
    },
    "jobs": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/job"
      }
    },
    "audit_events": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/auditEventReference"
      }
    }
  },
  "$defs": {
    "workflowLocalId": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9_\\-]{1,63}$"
    },
    "refName": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9_\\-./]{1,127}$"
    },
    "expression": {
      "type": "string",
      "minLength": 1
    },
    "serviceIdentity": {
      "type": "object",
      "required": [
        "type",
        "id",
        "delegation"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "service_account",
            "delegated_actor"
          ]
        },
        "id": {
          "type": "string"
        },
        "delegation": {
          "type": "object",
          "required": [
            "preserve_triggering_principal"
          ],
          "additionalProperties": false,
          "properties": {
            "preserve_triggering_principal": {
              "type": "boolean",
              "const": true
            }
          }
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "secretRef": {
      "type": "object",
      "description": "Pointer to centrally managed secret material. Raw secret values, tokens, keys, and credentials are not allowed in workflow definitions or fixtures.",
      "required": [
        "secret_ref",
        "purpose"
      ],
      "additionalProperties": false,
      "properties": {
        "secret_ref": {
          "type": "string",
          "pattern": "^sec_[0-9A-HJKMNP-TV-Z]{26}$"
        },
        "purpose": {
          "type": "string"
        }
      }
    },
    "integrationRef": {
      "type": "object",
      "required": [
        "integration_ref",
        "purpose"
      ],
      "additionalProperties": false,
      "properties": {
        "integration_ref": {
          "type": "string",
          "pattern": "^int_[0-9A-HJKMNP-TV-Z]{26}$"
        },
        "purpose": {
          "type": "string"
        }
      }
    },
    "policyCheck": {
      "type": "object",
      "required": [
        "action",
        "resource",
        "decision_ref"
      ],
      "additionalProperties": false,
      "properties": {
        "action": {
          "type": "string"
        },
        "resource": {
          "$ref": "#/$defs/resourceRef"
        },
        "decision_ref": {
          "$ref": "#/$defs/refName"
        }
      }
    },
    "retryPolicy": {
      "type": "object",
      "required": [
        "max_attempts",
        "backoff"
      ],
      "additionalProperties": false,
      "properties": {
        "max_attempts": {
          "type": "integer",
          "minimum": 1,
          "maximum": 10
        },
        "backoff": {
          "type": "string",
          "enum": [
            "none",
            "linear",
            "exponential"
          ]
        },
        "idempotency_required": {
          "type": "boolean"
        }
      }
    },
    "executionDefaults": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "timeout_seconds": {
          "type": "integer",
          "minimum": 1
        },
        "retry": {
          "$ref": "#/$defs/retryPolicy"
        }
      }
    },
    "concurrency": {
      "type": "object",
      "required": [
        "scope",
        "limit",
        "on_conflict"
      ],
      "additionalProperties": false,
      "properties": {
        "scope": {
          "type": "string",
          "enum": [
            "workflow",
            "working_group",
            "trigger"
          ]
        },
        "limit": {
          "type": "integer",
          "minimum": 1
        },
        "on_conflict": {
          "type": "string",
          "enum": [
            "queue",
            "cancel_new",
            "cancel_running"
          ]
        }
      }
    },
    "trigger": {
      "type": "object",
      "required": [
        "id",
        "type",
        "enabled"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "type": {
          "type": "string",
          "enum": [
            "cron",
            "webhook",
            "internal_event"
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "filters": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/expression"
          }
        },
        "cron": {
          "type": "object",
          "required": [
            "schedule",
            "timezone"
          ],
          "additionalProperties": false,
          "properties": {
            "schedule": {
              "type": "string",
              "minLength": 1
            },
            "timezone": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "webhook": {
          "type": "object",
          "required": [
            "integration_ref",
            "signature_verification",
            "replay_protection"
          ],
          "additionalProperties": false,
          "properties": {
            "integration_ref": {
              "$ref": "#/$defs/integrationRef"
            },
            "signature_verification": {
              "type": "object",
              "required": [
                "required",
                "algorithm",
                "secret_ref"
              ],
              "additionalProperties": false,
              "properties": {
                "required": {
                  "type": "boolean",
                  "const": true
                },
                "algorithm": {
                  "type": "string",
                  "enum": [
                    "hmac-sha256",
                    "ed25519"
                  ]
                },
                "secret_ref": {
                  "$ref": "#/$defs/secretRef"
                },
                "timestamp_header": {
                  "type": "string"
                },
                "signature_header": {
                  "type": "string"
                }
              }
            },
            "replay_protection": {
              "type": "object",
              "required": [
                "required",
                "dedupe_key",
                "window_seconds"
              ],
              "additionalProperties": false,
              "properties": {
                "required": {
                  "type": "boolean",
                  "const": true
                },
                "dedupe_key": {
                  "type": "string",
                  "enum": [
                    "event_id",
                    "delivery_id",
                    "signature_digest"
                  ]
                },
                "window_seconds": {
                  "type": "integer",
                  "minimum": 60,
                  "maximum": 86400
                }
              }
            }
          }
        },
        "internal_event": {
          "type": "object",
          "required": [
            "event_type"
          ],
          "additionalProperties": false,
          "properties": {
            "event_type": {
              "type": "string",
              "enum": [
                "issue.created",
                "issue.updated",
                "issue.status_changed",
                "comment.created",
                "user.created",
                "working_group.changed",
                "integration.changed",
                "skill.changed",
                "agent.changed",
                "provider.changed",
                "usage.limit_reached",
                "policy.decision_denied",
                "workflow.completed",
                "workflow.failed"
              ]
            }
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "cron"
              }
            }
          },
          "then": {
            "required": [
              "cron"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "webhook"
              }
            }
          },
          "then": {
            "required": [
              "webhook"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "internal_event"
              }
            }
          },
          "then": {
            "required": [
              "internal_event"
            ]
          }
        }
      ]
    },
    "approvalGate": {
      "type": "object",
      "required": [
        "id",
        "approver_scope",
        "required_before",
        "timeout_seconds",
        "on_timeout"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "approver_scope": {
          "type": "string",
          "enum": [
            "workflow_owner",
            "working_group_admin",
            "policy_named_role"
          ]
        },
        "required_before": {
          "type": "string",
          "enum": [
            "protected_side_effect",
            "workflow_activation",
            "manual_review"
          ]
        },
        "timeout_seconds": {
          "type": "integer",
          "minimum": 60
        },
        "on_timeout": {
          "type": "string",
          "enum": [
            "deny",
            "cancel_run"
          ]
        },
        "reason": {
          "type": "string"
        }
      }
    },
    "job": {
      "type": "object",
      "required": [
        "id",
        "name",
        "steps"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "needs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/workflowLocalId"
          }
        },
        "condition": {
          "$ref": "#/$defs/expression"
        },
        "timeout_seconds": {
          "type": "integer",
          "minimum": 1
        },
        "retry": {
          "$ref": "#/$defs/retryPolicy"
        },
        "policy": {
          "$ref": "#/$defs/policyCheck"
        },
        "steps": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/step"
          }
        }
      }
    },
    "step": {
      "type": "object",
      "required": [
        "id",
        "kind",
        "name",
        "side_effect"
      ],
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "kind": {
          "type": "string",
          "enum": [
            "agent_task",
            "approval_wait",
            "policy_check",
            "gateway_request",
            "integration_call",
            "mcp_call",
            "script",
            "artifact_write",
            "handoff",
            "audit_event"
          ]
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "uses": {
          "$ref": "#/$defs/refName"
        },
        "needs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/workflowLocalId"
          }
        },
        "condition": {
          "$ref": "#/$defs/expression"
        },
        "timeout_seconds": {
          "type": "integer",
          "minimum": 1
        },
        "retry": {
          "$ref": "#/$defs/retryPolicy"
        },
        "policy": {
          "$ref": "#/$defs/policyCheck"
        },
        "approval_gate_ref": {
          "$ref": "#/$defs/workflowLocalId"
        },
        "secret_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/secretRef"
          }
        },
        "integration_refs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/integrationRef"
          }
        },
        "with": {
          "$ref": "#/$defs/nonSecretInputObject"
        },
        "side_effect": {
          "type": "object",
          "required": [
            "classification"
          ],
          "additionalProperties": false,
          "properties": {
            "classification": {
              "type": "string",
              "enum": [
                "none",
                "read",
                "write",
                "protected"
              ]
            },
            "description": {
              "type": "string"
            }
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "side_effect": {
                "properties": {
                  "classification": {
                    "const": "protected"
                  }
                }
              }
            }
          },
          "then": {
            "required": [
              "approval_gate_ref"
            ]
          }
        }
      ]
    },
    "nonSecretInputObject": {
      "type": "object",
      "description": "Non-secret step inputs. Sensitive values must be represented through secret_refs or integration_refs.",
      "propertyNames": {
        "not": {
          "pattern": "([Aa][Pp][Ii][_-]?[Kk][Ee][Yy]|[Aa][Cc][Cc][Ee][Ss][Ss][_-]?[Tt][Oo][Kk][Ee][Nn]|[Rr][Ee][Ff][Rr][Ee][Ss][Hh][_-]?[Tt][Oo][Kk][Ee][Nn]|[Pp][Rr][Ii][Vv][Aa][Tt][Ee][_-]?[Kk][Ee][Yy]|[Cc][Ll][Ii][Ee][Nn][Tt][_-]?[Ss][Ee][Cc][Rr][Ee][Tt]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Cc][Rr][Ee][Dd][Ee][Nn][Tt][Ii][Aa][Ll])"
        }
      },
      "additionalProperties": {
        "$ref": "#/$defs/nonSecretInputValue"
      }
    },
    "nonSecretInputValue": {
      "oneOf": [
        {
          "type": "string",
          "not": {
            "pattern": "([Bb][Ee][Aa][Rr][Ee][Rr]\\s+[A-Za-z0-9._\\-]+|gh[pousr]_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9_\\-]{16,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|[Xx]-[Aa][Mm][Zz]-[Ss][Ii][Gg][Nn][Aa][Tt][Uu][Rr][Ee]=|[Xx]-[Gg][Oo][Oo][Gg]-[Ss][Ii][Gg][Nn][Aa][Tt][Uu][Rr][Ee]=|[?&][Ss][Ii][Gg][Nn][Aa][Tt][Uu][Rr][Ee]=)"
          }
        },
        {
          "type": "number"
        },
        {
          "type": "boolean"
        },
        {
          "type": "null"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/nonSecretInputValue"
          }
        },
        {
          "$ref": "#/$defs/nonSecretInputObject"
        }
      ]
    },
    "auditEventReference": {
      "type": "object",
      "required": [
        "type",
        "resource",
        "when"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "workflow.definition.validated",
            "workflow.trigger.accepted",
            "workflow.approval.requested",
            "workflow.protected_operation.approved",
            "workflow.protected_operation.denied",
            "workflow.run.completed",
            "workflow.run.failed"
          ]
        },
        "resource": {
          "$ref": "#/$defs/resourceRef"
        },
        "when": {
          "type": "string",
          "enum": [
            "validation",
            "trigger",
            "approval",
            "completion"
          ]
        }
      }
    }
  }
} as const;

export const contractSchemas = {
  "audit-event.schema.json": AuditEventSchema,
  "event-envelope.schema.json": EventEnvelopeSchema,
  "policy-decision.schema.json": PolicyDecisionSchema,
  "usage-event.schema.json": UsageEventSchema,
  "workflow-definition.schema.json": WorkflowDefinitionSchema
} as const;
