// Generated by scripts/generate-contracts.mjs. Do not edit by hand.

export const AuditEventSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/audit-event.schema.json",
  "title": "TaskOtterAuditEvent",
  "type": "object",
  "required": [
    "schema_version",
    "event_id",
    "working_group_id",
    "actor",
    "action",
    "resource",
    "outcome",
    "occurred_at"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "audit-event@0.1.0"
    },
    "event_id": {
      "type": "string",
      "pattern": "^aud_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "action": {
      "type": "string"
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "outcome": {
      "type": "string",
      "enum": [
        "allowed",
        "denied",
        "succeeded",
        "failed"
      ]
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "request_id": {
      "type": "string"
    },
    "policy_decision_id": {
      "type": "string"
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    }
  }
} as const;

export const PolicyDecisionSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/policy-decision.schema.json",
  "title": "TaskOtterPolicyDecision",
  "type": "object",
  "required": [
    "schema_version",
    "decision_id",
    "working_group_id",
    "actor",
    "action",
    "resource",
    "effect",
    "evaluated_at",
    "ttl_seconds",
    "constraints"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "policy-decision@0.1.0"
    },
    "decision_id": {
      "type": "string",
      "pattern": "^poldec_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "actor": {
      "$ref": "#/$defs/actorRef"
    },
    "action": {
      "type": "string",
      "examples": [
        "runner.job.execute",
        "gateway.provider.invoke"
      ]
    },
    "resource": {
      "$ref": "#/$defs/resourceRef"
    },
    "effect": {
      "type": "string",
      "enum": [
        "allow",
        "deny"
      ]
    },
    "reason_code": {
      "type": "string"
    },
    "evaluated_at": {
      "type": "string",
      "format": "date-time"
    },
    "ttl_seconds": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3600
    },
    "constraints": {
      "type": "object",
      "required": [
        "network_zones",
        "tool_scopes",
        "provider_model_ids",
        "max_runtime_seconds"
      ],
      "additionalProperties": false,
      "properties": {
        "network_zones": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "tool_scopes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "provider_model_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "max_runtime_seconds": {
          "type": "integer",
          "minimum": 1
        }
      }
    }
  },
  "$defs": {
    "actorRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "user",
            "agent",
            "service"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "resourceRef": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    }
  }
} as const;

export const UsageEventSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/usage-event.schema.json",
  "title": "TaskOtterUsageEvent",
  "type": "object",
  "required": [
    "schema_version",
    "event_id",
    "working_group_id",
    "source",
    "occurred_at",
    "subject",
    "measurements"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "usage-event@0.1.0"
    },
    "event_id": {
      "type": "string",
      "pattern": "^usevt_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "source": {
      "type": "string",
      "enum": [
        "control_plane",
        "runner",
        "gateway"
      ]
    },
    "occurred_at": {
      "type": "string",
      "format": "date-time"
    },
    "subject": {
      "type": "object",
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "agent_run",
            "gateway_request",
            "workflow_run"
          ]
        },
        "id": {
          "type": "string"
        }
      }
    },
    "measurements": {
      "type": "object",
      "required": [
        "duration_ms"
      ],
      "additionalProperties": false,
      "properties": {
        "duration_ms": {
          "type": "integer",
          "minimum": 0
        },
        "input_tokens": {
          "type": "integer",
          "minimum": 0
        },
        "output_tokens": {
          "type": "integer",
          "minimum": 0
        },
        "tool_invocations": {
          "type": "integer",
          "minimum": 0
        },
        "estimated_cost_micros": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "policy_decision_id": {
      "type": "string"
    },
    "idempotency_key": {
      "type": "string"
    }
  }
} as const;

export const WorkflowDefinitionSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://contracts.taskotter.dev/workflow-definition.schema.json",
  "title": "TaskOtterWorkflowDefinition",
  "type": "object",
  "required": [
    "schema_version",
    "workflow_id",
    "working_group_id",
    "name",
    "status",
    "triggers",
    "steps"
  ],
  "additionalProperties": false,
  "properties": {
    "schema_version": {
      "const": "workflow-definition@0.1.0"
    },
    "workflow_id": {
      "type": "string",
      "pattern": "^wfl_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "working_group_id": {
      "type": "string",
      "pattern": "^wg_[0-9A-HJKMNP-TV-Z]{26}$"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "type": "string",
      "enum": [
        "draft",
        "active",
        "disabled",
        "archived"
      ]
    },
    "triggers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "type"
        ],
        "additionalProperties": true,
        "properties": {
          "type": {
            "type": "string"
          }
        }
      }
    },
    "steps": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "id",
          "kind"
        ],
        "additionalProperties": true,
        "properties": {
          "id": {
            "type": "string"
          },
          "kind": {
            "type": "string",
            "enum": [
              "agent_task",
              "approval",
              "webhook",
              "gateway_request"
            ]
          }
        }
      }
    }
  }
} as const;

export const contractSchemas = {
  "audit-event.schema.json": AuditEventSchema,
  "policy-decision.schema.json": PolicyDecisionSchema,
  "usage-event.schema.json": UsageEventSchema,
  "workflow-definition.schema.json": WorkflowDefinitionSchema
} as const;
