// Generated by scripts/generate-contracts.mjs. Do not edit by hand.

export const controlPlaneContract = {
  "title": "TaskOtter Control Plane API",
  "version": "0.1.0",
  "basePath": "/api/v1",
  "operations": [
    {
      "operationId": "createIssue",
      "method": "POST",
      "path": "/issues",
      "tags": [
        "Issues"
      ]
    },
    {
      "operationId": "createIssueComment",
      "method": "POST",
      "path": "/issues/{issue_id}/comments",
      "tags": [
        "Comments"
      ]
    },
    {
      "operationId": "listAgents",
      "method": "GET",
      "path": "/agents",
      "tags": [
        "Agents"
      ]
    },
    {
      "operationId": "listAuditEvents",
      "method": "GET",
      "path": "/audit/events",
      "tags": [
        "Audit"
      ]
    },
    {
      "operationId": "listIntegrations",
      "method": "GET",
      "path": "/integrations",
      "tags": [
        "Integrations"
      ]
    },
    {
      "operationId": "listIssueComments",
      "method": "GET",
      "path": "/issues/{issue_id}/comments",
      "tags": [
        "Comments"
      ]
    },
    {
      "operationId": "listIssues",
      "method": "GET",
      "path": "/issues",
      "tags": [
        "Issues"
      ]
    },
    {
      "operationId": "listProviders",
      "method": "GET",
      "path": "/providers",
      "tags": [
        "Providers"
      ]
    },
    {
      "operationId": "listSkills",
      "method": "GET",
      "path": "/skills",
      "tags": [
        "Skills"
      ]
    },
    {
      "operationId": "listUsers",
      "method": "GET",
      "path": "/users",
      "tags": [
        "Users"
      ]
    },
    {
      "operationId": "listWorkflows",
      "method": "GET",
      "path": "/workflows",
      "tags": [
        "Workflows"
      ]
    },
    {
      "operationId": "listWorkingGroups",
      "method": "GET",
      "path": "/working-groups",
      "tags": [
        "WorkingGroups"
      ]
    },
    {
      "operationId": "recordUsageEvent",
      "method": "POST",
      "path": "/usage/events",
      "tags": [
        "Usage"
      ]
    }
  ]
} as const;

export type TaskOtterRequestOptions = {
  path?: Record<string, string>;
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
  body?: unknown;
};

export type TaskOtterFetch = (input: string, init: {
  method: string;
  headers: Record<string, string>;
  body?: string;
}) => Promise<{
  ok: boolean;
  status: number;
  text: () => Promise<string>;
}>;

export class TaskOtterApiError extends Error {
  readonly status: number;
  readonly response: unknown;

  constructor(status: number, response: unknown) {
    super(`TaskOtter API request failed with status ${status}`);
    this.status = status;
    this.response = response;
  }
}

export class TaskOtterClient {
  readonly baseUrl: string;
  readonly fetchImpl: TaskOtterFetch;

  constructor(options: { baseUrl?: string; fetch?: TaskOtterFetch } = {}) {
    this.baseUrl = options.baseUrl ?? controlPlaneContract.basePath;
    this.fetchImpl = options.fetch ?? fetch;
  }

  createIssue(options: TaskOtterRequestOptions = {}) {
    return this.request("POST", "/issues", options);
  }

  createIssueComment(options: TaskOtterRequestOptions = {}) {
    return this.request("POST", "/issues/{issue_id}/comments", options);
  }

  listAgents(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/agents", options);
  }

  listAuditEvents(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/audit/events", options);
  }

  listIntegrations(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/integrations", options);
  }

  listIssueComments(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/issues/{issue_id}/comments", options);
  }

  listIssues(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/issues", options);
  }

  listProviders(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/providers", options);
  }

  listSkills(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/skills", options);
  }

  listUsers(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/users", options);
  }

  listWorkflows(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/workflows", options);
  }

  listWorkingGroups(options: TaskOtterRequestOptions = {}) {
    return this.request("GET", "/working-groups", options);
  }

  recordUsageEvent(options: TaskOtterRequestOptions = {}) {
    return this.request("POST", "/usage/events", options);
  }

  async request(method: string, route: string, options: TaskOtterRequestOptions = {}): Promise<unknown> {
    const url = this.buildUrl(route, options);
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(options.query ?? {})) {
      if (value !== undefined) query.set(key, String(value));
    }
    const requestUrl = query.size === 0 ? url : `${url}?${query.toString()}`;

    const headers = {
      accept: "application/json",
      ...(options.body === undefined ? {} : { "content-type": "application/json" }),
      ...(options.headers ?? {})
    };

    const response = await this.fetchImpl(requestUrl, {
      method,
      headers,
      ...(options.body === undefined ? {} : { body: JSON.stringify(options.body) })
    });
    const responseText = await response.text();
    const parsed = responseText.length === 0 ? undefined : JSON.parse(responseText);
    if (!response.ok) throw new TaskOtterApiError(response.status, parsed);
    return parsed;
  }

  private interpolatePath(route: string, params: Record<string, string> = {}): string {
    return route.replace(/\{([^}]+)\}/g, (_match, name) => {
      const value = params[name];
      if (!value) throw new Error(`Missing path parameter: ${name}`);
      return encodeURIComponent(value);
    });
  }

  private buildUrl(route: string, options: TaskOtterRequestOptions): string {
    const base = this.baseUrl.replace(/\/$/, "");
    const path = this.interpolatePath(route, options.path);
    if (base.length === 0) return path;
    return `${base}${path.startsWith("/") ? path : `/${path}`}`;
  }
}
